import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

/**
 * FOR ALL CASES:
 *      Length: left to right
 *      Width : top to bottom
 */

public class Main {

    public static void main(String[] args) {
        System.out.println("Hello");

        ArrayList<Rectangle> list = new ArrayList<>();

        Scanner scanner;
        try {
            scanner = new Scanner(new File("./src/instance.txt"));
            read(scanner, list);
            Scanner reader = new Scanner(System.in);

            boolean go = true;
            int option = 0;
            while (go) {
                System.out.println("Please select an option: ");
                System.out.println("1: Find a pretty good solution");
                System.out.println("2: Find an exact solution");
                option = reader.nextInt();
                long time1, time2;
                switch (option) {
                    case 1:
                        System.out.println("Finding a pretty good solution....");
                        time1 = System.currentTimeMillis();
                        prettyGoodSolution();
                        time2 = System.currentTimeMillis();
                        System.out.println((time2 - time1) + "ms");
                        go = false;
                        break;
                    case 2:
                        System.out.println("Finding a exact solution....");
                        time1 = System.currentTimeMillis();
                        exactSolution(list);
                        time2 = System.currentTimeMillis();
                        System.out.println((time2 - time1) + "ms");
                        go = false;
                        break;
                    default:
                        System.out.println("Invalid option");
                        break;
                }
            }

            reader.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            System.out.println("You're missing instance.txt");
        }
        System.out.println("done!");
    }

    private static void read(Scanner scanner, ArrayList<Rectangle> list) {
        while (scanner.hasNextLine()) {
            Scanner scanLine = new Scanner(scanner.nextLine());
            scanLine.useDelimiter(" ");
            if (scanLine.hasNext()) {
                int length = Integer.parseInt(scanLine.next());
                int width = Integer.parseInt(scanLine.next());
                list.add(new Rectangle(length, width));
            }
            scanLine.close();
        }
    }

    /**
     * Solves for the exact solution of the PackingProblem
     * <p>
     * The general idea for this is to start with the minimum area
     * generated by the sum of the areas of the rectangles. When
     * it is realized that a progression will not work, then abort
     * and expand the smaller side (and shrink the larger side).
     * This continues until all possible dimensions are attempted.
     * If an answer has yet to be found, then increase the area.
     * <p>
     * This process is going to be done over the following steps:
     * 1. Find the minimum side (minSide, length or width)
     * 2. Find the minimum area (minArea)
     * 3. Try a packing rectangle of minArea with minSide
     * 4. Try to pack rectangles
     * 5. If this fails, lengthen minSide and return to step 3
     * 6. If minSide becomes too large then increase minArea
     * * ie: when minArea/minSide >= minOtherSide
     * 7. The first successful rectangle packing is the minimum
     */
    public static void exactSolution(ArrayList<Rectangle> list) {

        // First: Find minSide
        int minLength = findMinLength(list);
        int minWidth = findMinWidth(list);
        boolean usingLength = false;
        if (minLength <= minWidth) {
            usingLength = true;
        }

        // Second: Find minArea
        int minArea = findMinArea(list);
        int currentArea = minArea;

        // Third: Figure packing parameters
        int length = 0, width = 0;

        // Fourth: Try a packing
        PackingRectangle pack;
        Collections.sort(list, Rectangle.areaComparator);

        do {
            if (usingLength) {
                do {
                    length++;
                } while (currentArea % length != 0 && length < currentArea/2);
                width = currentArea/length;
            } else {
                do {
                    width++;
                } while (currentArea % width != 0 && width < currentArea/2);
                length = currentArea/width;
            }
            // Sixth: Try new Area
            if (length >= currentArea/minLength || width >= currentArea/minWidth) {
                currentArea++;
                length = minLength;
                width = minWidth;
            }
            // Fifth: Try new parameters
            pack = new PackingRectangle(length, width);
        } while (!someonePackThis(pack, list));
        pack.toStringPack();
    }

    // finds the min length
    private static int findMinLength(ArrayList<Rectangle> list) {
        //just initialize it to first length
        int minLength = list.get(0).getLength();
        for (int i = 1; i < list.size(); i++) {
            if (minLength < list.get(i).getLength()) {
                minLength = list.get(i).getLength();
            }
        }
        return minLength;
    }

    // finds the min width
    private static int findMinWidth(ArrayList<Rectangle> list) {
        //just initialize it to first length
        int minWidth = list.get(0).getLength();
        for (int i = 1; i < list.size(); i++) {
            if (minWidth < list.get(i).getLength()) {
                minWidth = list.get(i).getLength();
            }
        }
        return minWidth;
    }

    // finds the min area
    private static int findMinArea(ArrayList<Rectangle> list) {
        int minArea = 0;
        for (int j = 0; j < list.size(); j++) {
            minArea+=list.get(j).getArea();
        }
        return minArea;
    }

    /**
     * attempts to fit all rectangles into pack (length x width)
     * This works as follows:
     * 1. Create pack
     * 2. Sort rectangles by area
     * 3. Recursively try to fit rectangles into pack
     *
     * This first method is the driver
     */
    private static boolean someonePackThis(PackingRectangle pack, ArrayList<Rectangle> list) {
        boolean doesFit = false;
        if (list.isEmpty()) {
            doesFit = true;
        } else {
            for (int i = 0; i < list.size() && !doesFit; i++) {
                doesFit = someonePackThis(pack, list, i);
            }
        }
        return doesFit;
    }

    private static boolean someonePackThis(PackingRectangle pack, ArrayList<Rectangle> list, int index) {
        boolean doesFit = false;

        // Terminate recursions upon reaching last element, note this doesn't always conclude recursion
        if (pack.howManyRectanglesPacked() == list.size()-1) {
            int i = 0;
            while (i < list.size() && list.get(i).isUsed()) {
                i++;
            }
            list.get(i).useThisRectangle();
            doesFit = pack.whereWillThisFit(list.get(i));
            if (!doesFit) {
                list.get(i).dontUseThisRectangle();
            } else {
                pack.flipRectangle(list.get(i).getAddedRow(), list.get(i).getAddedCol(), list.get(i));
            }
        } else {
            int i = index, k = 0;
            while(k < list.size() && !doesFit && !list.get(i).isUsed() && pack.howManyRectanglesPacked() < list.size() && pack.whereWillThisFit(list.get(i))) {

                // identify the rectangle to be packed
                list.get(i).useThisRectangle();

                // pack the rectangle
                pack.flipRectangle(list.get(i).getAddedRow(), list.get(i).getAddedCol(), list.get(i));

                // recursively pack another rectangle
                doesFit = someonePackThis(pack, list, ((i+1)%list.size()));

                // if the recursion doesn't give a packed rectangle then remove this rectangle
                if (!doesFit) {
                    list.get(i).dontUseThisRectangle();
                    pack.flipRectangle(list.get(i).getAddedRow(), list.get(i).getAddedCol(), list.get(i));
                }
                i++;
                k++;
                if (i >= list.size()) {
                    i = i%list.size();
                }
            }
        }
        return doesFit;
    }

    private static void prettyGoodSolution() {
        // TODO Auto-generated method stub

    }

}